### ISSUE TITLE
Static setions declaration

### ISSUE THREAD

**Issue by seostudio** [Section214/S214-Settings#1]
Hi,

static declaration of $sections variable makes this class unuseable when we need multiple instances of class.

Please change code:

`private function get_registered_settings_sections() {
        static $sections = false;
        if( $sections !== false ) {
            return $sections;
        }
        $sections = apply_filters( $this->func . '_registered_settings_sections', array() );
        return $sections;
    }`

to 

`private function get_registered_settings_sections() {
        global ${$this->func . '_sections'};

```
    if ( !empty( $sections ) ) {
        return $sections;
    }

    $sections = apply_filters( $this->func . '_registered_settings_sections', array() );

    return $sections;
}`
```

**Comment by evertiro** [comment]
@seostudio GitHub kinda messed up your code there... mind submitting a PR?

**Comment by evertiro** [comment]
Merged!
